[[language]]
name = "html"
formatter = { command = "npx", args = ["prettier", "--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "npx", args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = "npx", args = ["prettier", "--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript", "--tab-width", "2"]}
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
language-servers = ["ruff", "pyright"]
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = false

[language-server.bzl]
command = "bzl"
args = ["lsp", "serve"]

[[language]]
name = "starlark"
language-servers = ["bzl"]
auto-format = true
